### ISSUE TITLE
Track Settings Button

### ISSUE THREAD

**Issue by samstorment** [thomasjonesmc/send-a-demo#13]
Add a button to tracks that show expanded information about the track. 

Some suggestions:
* Full Track Name - in case it is too long and hidden
* Track Author Name 
* Track Length
* Track Start Time

**Comment by samstorment** [comment]
I think it might be better to make this a track settings button, similar to the demo settings button. This way a user could change the title of their track and potentially change other track data if more is added in the future.

**Comment by thomasjonesmc** [comment]
> I think it might be better to make this a track settings button, similar to the demo settings button. 

I think that's a good idea, track settings it is!
